### ISSUE TITLE
erratic cursor and display in emacs

### ISSUE THREAD

**Issue by christianpaquin** [Microsoft/console#283]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.1] 
Windows 10, version 1809 installed on Oct 4, 2018.

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

1. I installed Ubuntu 18.04 from the Windows Store, and "sudo apt-get emacs" (v25.2.2 was installed)
2. open a file larger than the console height (I used a large C file)
3. start moving the cursor using alt-f (to move forward word to word); at some point the cursor visually jumps at the end of line but actually remains where it is supposed to be (hitting ctrl-l to re-center the screen around the current line refreshed the screen correctly)
4. when editing the text, the display gets garbled, the letters appearing on subsequent lines. This only affects the buffer visually, the logical buffer is ok ((hitting ctrl-l to re-center the screen around the current line refreshed the screen correctly)

* What's wrong / what should be happening instead:
The cursor becomes erratic and the display gets garbled after moving the cursor and moving down the file. This started happening after the 1809 update.

PS: this seems to be the same behavior as in [WSL's issue 3587](https://github.com/Microsoft/WSL/issues/3587)

**Comment by Erebuxy** [comment]
Have the same problem here in Vim, Tmux etc. after recent Window 10 Pro insider preview update (Ver 1809 Build 10.0.18252.1000).
I think a simple fix is to stop the cursor blinking. Is there any way to do that?

**Comment by christianpaquin** [comment]
> I think a simple fix is to stop the cursor blinking. Is there any way to do that?

I experience the same problem if I start emacs with no blinking cursor (-nbc)

**Comment by Erebuxy** [comment]
> > I think a simple fix is to stop the cursor blinking. Is there any way to do that?
> 
> I experience the same problem if I start emacs with no blinking cursor (-nbc)

I believe this is the same as Microsoft/console#269.

**Comment by zadjii-msft** [comment]
> 3. start moving the cursor using alt-f (to move forward word to word); at some point the cursor visually jumps at the end of line but actually remains where it is supposed to be (hitting ctrl-l to re-center the screen around the current line refreshed the screen correctly)
> 4. when editing the text, the display gets garbled, the letters appearing on subsequent lines. This only affects the buffer visually, the logical buffer is ok ((hitting ctrl-l to re-center the screen around the current line refreshed the screen correctly)

These two are what makes me think it's different than #269. My gut tells me that there's something new in 18.04's termcap that we don't support yet. 
I've filed MSFT:19302368 internally to make sure this gets looked at.

**Comment by christianpaquin** [comment]
> My gut tells me that there's something new in 18.04's termcap that we don't support yet.

FYI, I experience the same thing in my original "Bash on Ubuntu on Windows" install; I tried installing the 18.04 store app (and documented it as such in the repro steps) to see if I had the same problem.

**Comment by uhengart** [comment]
I'm also observing this problem. However, I don't think it's tied to Ubuntu 18.04. The problem started occurring after the W10 1809 upgrade while still running Ubuntu 16.04 in WSL. 

I just upgraded Ubuntu 16.04 in WSL to 18.04 on a second machine, which hasn't been upgraded to W10 1809. The problem doesn't occur there for either version of Ubuntu.

**Comment by zadjii-msft** [comment]
I think I have a beat on the change that broke this. I believe it has to do with the tab stops. I know emacs will sometime use tab to advance the cursor to the next tab-stop, instead of positioning the cursor manually. It seems like there's some scenario where the tab stops aren't properly getting set, which means instead of the cursor moving to the next tab stop (usually every 8 columns), the console is moving the cursor to the end of the line. It's this disconnect between where emacs believes the cursor is and where the cursor actually is that's causing these problems.

Theoretically, a `TERM` setting that doesn't use the tabstops should fix this, though I don't know which setting would be most appropriate, or exactly which sequence is broken currently. It's probably a combination of `tbc` and `hts`.

I don't have a fix yet, but I'll keep this thread posted with updates.

**Comment by zadjii-msft** [comment]
Okay, so I am fairly sure I found the source of this. In RS5 during the course of other tab-stop fixes, we forgot to setup the default tabstop positions on the alt buffer. The fix is really simple, so once I get a test on it, it should be on it's way to Insider's soon.

**Comment by miniksa** [comment]
Probably early to mid January in Insiders builds.

**Comment by PgAuffret** [comment]
Thank you :)

**Comment by mgennari** [comment]
While it is suggested that an early to mid January fix would be inbound in the Insiders build, what might the timeline look like for a Windows 1809 fix?

Note:
For those afflicted with this issue, I reccomend setting TERM to xterm-color as this improves the behaviour drastically, however it is still dysfunctional.

**Comment by miniksa** [comment]
By default, we don't port things back to Windows builds that have already RTM'd unless they're causing a security issue, significant end-user impact, or have some other business justification. Servicing a released OS is not free, so it's generally limited to what's absolutely necessary.

**Comment by mgennari** [comment]
Thank you for the information! Will any information about a fix be made public such that we can implement it ourselves? I rely on the functionality pretty heavily for research work, so any improvements are welcomed.

**Comment by bubbleguuum** [comment]
Is there any workaround on 1809 for this annoying bug until a fixed WSL is available ? This makes emacs entirely unusable.

**Comment by miniksa** [comment]
This is fixed in Insiders 18309 and higher.

**Comment by lafredin** [comment]
Is this seriously not going to be fixed in the regular build? My company settings don't allow me to use Insiders and this is making Linux practically unusable.

**Comment by DHowett-MSFT** [comment]
Hi @lafredin,
We haven't been able to build up a compelling case (that is: one that provably impacts a business's ability to ship Windows or for an enterprise to onboard their users) to start the servicing pipeline to take this bugfix downlevel. Really sorry about that!

**Comment by lafredin** [comment]
@DHowett-MSFT this is a serious usability issue though. It has been around for months and has a known fix. Honestly emacs is completely unusable with the cursor and line skipping. The whole idea of WSL was to give a usable Linux environment natively on a Windows computer to not force people to use clunky 3rd party options or VMs or switch to a Mac...not updating non-Insiders' user experience seems totally counter to this

**Comment by bubbleguuum** [comment]
It's unfortunate that this issue cannot be hotfixed in current version of Windows, especially since it was not an issue in 1803. Among other issues with WSL (notably slow I/O, Console not supporting tabs), this is what made me switch recently to full blown Linux for development...

**Comment by PgAuffret** [comment]
Hi,
I'm not quite sure to understand. Will the next regular update fix it?
Thank you

**Comment by zadjii-msft** [comment]
@PgAuffret Yes, whatever the next version of Windows after 1809 is will contain the fix for this issue.

**Comment by saraheno** [comment]
I am currently having this problem.  Windows tells me it is version 10.0.17763 build 17763.  Which of these digits would correspond to 1809?  Also, Windows tells me it is up to date, so I assume this is after 1809?

**Comment by zadjii-msft** [comment]
@saraheno Unfortunately Windows' naming scheme is super confusing, so hopefully this chart will clear things up:
![image](https://user-images.githubusercontent.com/18356694/53821149-0a8d9680-3f22-11e9-991c-340e098884ce.png)
(see [wikipedia](https://en.wikipedia.org/wiki/Windows_10_version_history))

Version 1809 is build 17763.*

Anything that's version 1809 will have this bug.

The fix is available in Insiders builds of 19H1, which doesn't yet have an official version or build number. Any Insider's builds above 10.0.18309 will have the fix.

**Comment by Steven-Wright** [comment]
setting TERM to vt100 sufficed to get the basic emacs navigation working (C-f, Alt-f, etc.)

**Comment by mathieufortin01** [comment]
:point_up: :point_up: this is the temporary workaround that works.

**Comment by saraheno** [comment]
Thank you!

**Comment by thcoffee-msft** [comment]
For affected users, I have found that setting TERM=rxvt produces better behavior than any of the options mentioned above.

I tried this on the basis of a [comparison table](https://en.wikipedia.org/wiki/Comparison_of_terminal_emulators) on Wikipedia, searching for options that supported color but not tab stops. This is clearly not the whole story, but I have very little knowledge of terminal implementations.

**Comment by quarkgluons** [comment]
> For affected users, I have found that setting TERM=rxvt produces better behavior than any of the options mentioned above.
> 
> I tried this on the basis of a [comparison table](https://en.wikipedia.org/wiki/Comparison_of_terminal_emulators) on Wikipedia, searching for options that supported color but not tab stops. This is clearly not the whole story, but I have very little knowledge of terminal implementations.

This one worked for me as well.

**Comment by diracyoon** [comment]
Please please fix it asap!!! WSL became effectively useless. Even with latest version of 1809 17763.437, emacs cursor doesn't work properly.

**Comment by zadjii-msft** [comment]
Please read the thread before replying. 

## The fix is in any Insiders builds above 10.0.18309, and will ship officially with the May2019 release, version 1903

There are a number of workarounds mentioned in the thread, including setting the `TERM` envvar to either `rxvt` or `vt100`.

**Comment by zendevil** [comment]
We are still waiting

**Comment by Summon528** [comment]
@zendevil Windows 10 1903 just recently released, you can get it [here](https://www.microsoft.com/software-download/windows10) if you don't want to wait anymore

**Comment by diracyoon** [comment]
After update windows 10 to 1903 version, the bug became better. However still not fixed perfectly.

**Comment by zadjii-msft** [comment]
@diracyoon could you file a new issue with exact repro steps and a description (preferably screenshots) of what's wrong? The specific issue described by this thread was fixed in 1903, and I'd rather have a new thread to track the new bug, even if it does have a similar symptom.

**Unless of course #1474 is an exact description of the problem you're seeing.**

**Comment by thcoffee-msft** [comment]
After upgrading to 1903, I find that Emacs remains unusable with the default TERM=xterm-256color. Here's an example with screenshots for illustration:

1. Start WSL Debian, enter `emacs -q -nw`, open file larger than console (example: C-x C-f .bashrc). So far so good:

![image](https://user-images.githubusercontent.com/48807454/61231223-9093c800-a6e0-11e9-9df0-ba3a68f53fad.png)

2. Search for text beyond the end of the console (example for my .bashrc: C-s gu). Text begins to be shuffled:

![image](https://user-images.githubusercontent.com/48807454/61231402-f5e7b900-a6e0-11e9-84ba-6d075c469531.png)

3. Continuing search text entry (in this example, extending "gu" to "gurob"), there's additional shuffling:

![image](https://user-images.githubusercontent.com/48807454/61231545-2deefc00-a6e1-11e9-93de-7eeb5ddf97c2.png)

4. Here's the text that appears when attempting to scroll to the end of the file. Different bits are shuffled instead:

![image](https://user-images.githubusercontent.com/48807454/61231682-74445b00-a6e1-11e9-91ca-9ee26fff1803.png)

5. For reference, here's what the actual end of the file looks like:

![image](https://user-images.githubusercontent.com/48807454/61232588-87582a80-a6e3-11e9-8310-61df9d241be3.png)

This is the easiest example I could construct, but the shuffling behavior is pervasive. Almost anytime Emacs is rewriting irregular portions of the terminal, text may be shifted from places it previously appeared into areas where no text should appear. Once spurious text is on the loose, it generally persists through scrolling until overwritten, eventually leading files to appear as a soup of text fragments. And any features that rely on dynamically resizing multiple buffers (such as the minibuffer) are nearly hopeless to use, as lines don't even appear in the right places.

I haven't identified a precise pattern to explain the observed behavior, but I'm sure that anyone who attempts to make any substantial use of Emacs on WSL will encounter these bizarre effects. They make it impossible to do any work in console Emacs without downgrading the terminal to, e.g., rxvt, which is substantially inferior in color and keyboard support.

**Comment by thcoffee-msft** [comment]
Thanks to https://github.com/microsoft/terminal/issues/1474#issuecomment-504765389 from @sandric, I've found that `tmux` resolves these issues, so I will probably use this workaround for the time being.

**Comment by sandric** [comment]
@thcoffee-msft actually that is pretty strange advice meaning name of repo, though, I found that smth like multiple-cursors still working with glitches no matter how I tried in new term preview, so my humble suggestion to other emacs guys like me - switch to wsltty for now, latest updates works with WSL2 via standard windows console, and it works flawlessly for me.

**Comment by mhairifin** [comment]
If other people are still experiencing problems, so far TERM=konsole has produced the least issues for me

**Comment by kiyoMatsui** [comment]
Thanks mhairifin, you have saved me from zile purgatory.
For those who just want things to work. add: TERM=konsole 
at the end of your .bashrc file and it just works!

**Comment by calbaker** [comment]
Adding `export TERM=rxvt` to my ~/.bashrc file worked great.   You can also run this command in terminal to test it out.  Adding it to ~/.bashrc will be persistent.

**Comment by thcoffee-msft** [comment]
Just to update the thread, the workflow that continues to resolve all these problems for me (and avoids the color downgrade of `rxvt`) is something like:
1. `tmux`
2. `export TERM=xterm-256color`
3. `emacs -nw`

The only annoyance of using emacs through tmux is that tmux binds `C-b` as a prefix key by default, which can be resolved by binding a different key in `~/.tmux.conf`, such as:
```
unbind C-b
set-option -g prefix M-'\'
```

**Comment by PieterPaulussen** [comment]
Having similar issues with suckless st's terminal... Sigh

**Comment by tbaggaley** [comment]
Still having this issue (garbled emacs display occasionally on scrolling / using other split windows within emacs) with Windows Terminal Preview 1.6.10412.0 and WSL2.

Using tmux and `TERM=xterm-256color` doesn't seem to fix it for me, sadly.

**Comment by zadjii-msft** [comment]
@tbaggaley could you file a new issue with exact repro steps and a description (preferably screenshots) of what's wrong? The specific issue described by this thread was fixed in conhost in 1903 (before the Terminal even existed), and I'd rather have a new thread to track the new bug, even if it does have a similar symptom.

**Comment by ThoshHub** [comment]
> Adding `export TERM=rxvt` to my ~/.bashrc file worked great. You can also run this command in terminal to test it out. Adding it to ~/.bashrc will be persistent.

This worked for me, thanks!!
