### ISSUE TITLE
Ambiguous width character processing

### ISSUE THREAD

**Issue by ntak** [Microsoft/console#347]
Embed ConPTY in vim.exe. Input of ambiguous width character is incorrect. Is it related to the code page value being 0?
Whose job is to fix it? Vim's existing code? Me? Or is it you?

**Comment by ntak** [comment]
https://github.com/vim/vim/pull/3794

**Comment by miniksa** [comment]
I don't understand what you're asking. The console host always has a codepage value.

If you're using ConPTY, the pipes involved always accept text encoded as UTF-8 a.k.a. Codepage 65001 and it's not configurable. 

But the client application attached on the other side will have a codepage per normal console application hosting rules.

As for ambiguous width characters, which character in particular are you having trouble with? We have some amount of support for ambiguous width characters based on the font being presented to the client application. I'd need a specific example to figure out what exactly is going wrong and whose job it would be to fix it.

**Comment by ntak** [comment]
I'm very sorry, I was sleepy. I wonder why I thought this would be conveyed to others...

When executing chcp in ConPTY, 0 is returned, and when GetACP() is used, 0 is returned.

This is a movie that inputs "★" ambiguous character in Japanese environment. Please see the position of the cursor.
The upper half of the screen is ConPTY and the lower half is winpty.

![c__windows_system32_cmd](https://user-images.githubusercontent.com/44701315/51181164-c14f9c00-190d-11e9-96a6-f46a16038c70.gif)

In ConPTY, when the flowing sequence contains the change of the cursor position, if it is displayed as it is, the cursor moves only to the right by one cell.
In winpty, there is no such sequence, so the cursor will advance to the right by two cells.
I tried quite hard, but I could not advance the cursor to the right by 2 cells with ConPTY.

It is confirmed that it is not a problem of the glyph width of the font.

**Comment by miniksa** [comment]
OK, @zadjii-msft and I reproduced this issue this morning. I've filed MSFT:20197586 internally to try to figure out what's going on with the codepage of 0 when ConPTY loads up, which should solve this problem.

**Comment by miniksa** [comment]
I've submitted a fix that will resolve the codepage being 0 when ConPTY loads up which resolved this issue. It should reach Insiders builds within a few weeks.

**Comment by DHowett-MSFT** [comment]
This fix came out with Windows Insider Build 18334! Thanks!

**Comment by mattn** [comment]
This should not close since the issue of ambiguous width is not solved.

**Comment by mattn** [comment]
Ah, https://github.com/Microsoft/console/issues/370 is opened again.
