### ISSUE TITLE
ANSI/VT \e[7m and \e[27m (reverse/negative) do not work correctly after 24-bit color has been used

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#78]
_From @PhMajerus on October 20, 2017 18:23_

Concerns Redstone 3 RTW / Windows 10 ver. 1709, tested on build 16299.19. Affects all WSL distros and more broadly, all Win32 CUI apps using VT.

VT escape control sequences "\x1B[7m" and "\x1B[27m" are used to turn reverse video ("negative", but not technically negative) on and off.
They work fine until the console processed a 24-bit color "\x1B[38;2;r;g;bm" or "\x1B[48;2;r;g;bm". At that point, negative off (27) has no effect or even acts erratically, even if the color has been reset ("\x1B[39m", set back to a base 16 color (\x1B[3(0-9)m"), or if SGR has been reset ("\x1B[m") in the meantime.

`echo -e "\e[7m Reversed \e[27m Normal \e[38;2;250;20;40m 24-bit \e[36m 16-colors \e[7m Reversed \e[27m Normal \e[39m Default \e[7m Reversed \e[27m Normal \e[m Reset \e[7m Reversed \e[27m Normal"`

![vt reverse bug ubuntu rtw](https://user-images.githubusercontent.com/25664275/31836014-1e87339a-b5d4-11e7-880b-e185be2d9aa8.png)

This is a bug in conhost that affects all Windows CUI apps that uses VT, as the following repro code shows:
```
#include <windows.h>

#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif

int main()
{
	HANDLE hOutput = GetStdHandle(STD_OUTPUT_HANDLE);
	
	DWORD dwMode = 0;
	GetConsoleMode(hOutput, &dwMode);
	dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
	SetConsoleMode(hOutput, dwMode);
	
	LPTSTR pszTestString = TEXT("\x1B[7m Reversed \x1B[27m Normal \x1B[38;2;128;5;255m Set 24-bit foreColor \x1B[7m Reversed \x1B[27m Normal \r\n");
	WriteConsole(hOutput, pszTestString, _tcslen(pszTestString), NULL, NULL);
	
	getchar();
	return 0;
}
```
![reversevideo app](https://user-images.githubusercontent.com/25664275/31836497-cfd50ea0-b5d5-11e7-92da-f84a47d9c77d.png)

Calling SetConsoleScreenBufferInfoEx or showing and OK'ing the console's properties dialog seems to reset the issue until next time 24-bit color is used.

_Copied from original issue: Microsoft/WSL#2583_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on January 4, 2018 21:46_

Fix is in code review now.

@PhMajerus Thanks for the great writeup :) It's always so much easier to fix things when the problem is so well isolated with excellent repro steps.

**Comment by bitcrazed** [comment]
_From @PhMajerus on February 8, 2018 1:22_

@zadjii-msft Thanks for looking into it and fixing it.
Do you know when the fix might appear in insider build? I'm still seeing the issue in 17093 and would hate for something to go wrong and get unnoticed until it's too late for RS4.

**Comment by bitcrazed** [comment]
Should now be fixed in Win10 Spring 2018 Update. Let us know if you can repro in 1803 or newer builds.

**Comment by PhMajerus** [comment]
@bitcrazed Challenge accepted:
echo -e "\e[31m1\e[7m2\e[44m3\e[49m4\e[27m5\e[m"
echo -e "\e[38;2;250;20;40m 24-bit used \e[m"
echo -e "\e[31m1\e[7m2\e[44m3\e[49m4\e[27m5\e[m"
![vt 24bit rs4 rtw bug](https://user-images.githubusercontent.com/25664275/39673934-ff8e098e-5144-11e8-94f1-634c4617a731.png)

**Comment by zadjii-msft** [comment]
Maybe it re-regressed? I'll take a look. There's a lot of delta around the text buffer attributes right now, so it's possible we regressed this in new and interesting ways

**Comment by PhMajerus** [comment]
@zadjii-msft I saw you flagged this as RS5 milestone, does it mean it has been prioritized to be fixed in the upcoming release?
I'm getting concerned as there is no mention of it getting fixed and the bug is still present in build 17735 (pushed today to fast ring). This really makes using 24-bit colors problematic, and if it misses the deadline I'm afraid we'll have to wait until 19H1.

**Comment by DHowett-MSFT** [comment]
I think the fix for this went out in one of the 19H1 insider builds. Thanks for the report!
